[build]
  functions = "./"

[functions]
  node_version = "18"

[functions.handler]
  memory = "1024"
  timeout = "10"
  environment = {
    MONGO_URI = "${{secrets.MONGO_URI}}",
    COOKIE_KEY = "${{secrets.COOKIE_KEY}}",
    NODE_ENV = "production"
  }
